### ISSUE TITLE
3.2.1.154失败

### ISSUE THREAD

**Issue by aaq1adqwe** [x1hy9/WeChatUserDB#1]
2022-06-07 11:32:27,147 - pymem - DEBUG - Process 5688 is being debugged
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    getuserinfo(p)
  File "main.py", line 60, in getuserinfo
    base_address=pattern_scan_all(p.process_handle, bytes_path, return_multiple=True)
  File "main.py", line 38, in pattern_scan_all
    return_multiple=return_multiple
TypeError: scan_pattern_page() got an unexpected keyword argument 'return_multiple'

**Comment by lovvk3y** [comment]
D:\program\Python37_64\python.exe G:/Pyrhonpro/WeChatUserDB-main/WeChatUserDB-main/main.py
Traceback (most recent call last):
  File "D:\program\Python37_64\lib\site-packages\pymem\__init__.py", line 410, in read_bytes
    value = pymem.memory.read_bytes(self.process_handle, address, length)
  File "D:\program\Python37_64\lib\site-packages\pymem\memory.py", line 105, in read_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Pyrhonpro/WeChatUserDB-main/WeChatUserDB-main/main.py", line 126, in <module>
    getuserinfo(p)
  File "G:/Pyrhonpro/WeChatUserDB-main/WeChatUserDB-main/main.py", line 79, in getuserinfo
    wxid = p.read_bytes(wxid_addr, int_wxid_len)
  File "D:\program\Python37_64\lib\site-packages\pymem\__init__.py", line 412, in read_bytes
    raise pymem.exception.MemoryReadError(address, length, e.error_code)
pymem.exception.MemoryReadError: Could not read memory at: 1752066423, length: 6 - GetLastError: 299

进程已结束,退出代码1

**Comment by x1hy9** [comment]
经过测试我也发现了一些bug，问题的原因是因为某些情况下微信私钥地址小于微信基址导致无法搜索到，但是绝大数情况下应该是大于此基址，可以通过关闭微信进程重新登陆获取正确的key，还有一部分原因是极早微信版本下偏移量的变化导致无法搜索到key，可通过更新到最新版本解决问题。

**Comment by Alive24** [comment]
同样获取key失败。调试环境中，代码版本为v1.0.0， PC微信版本是3.7.6.44（当前2022-11-01最新），使用的是Windows 11。Python版本为3.8.3，并且在获取失败后关掉了`WeChat.exe`进程，再重启登录。

尝试通过打断点，在`def getuserinfo(p) -> (int, str)`内，通过以下代码第一次获取base_address:
```python
bytes_path = b'-----BEGIN PUBLIC KEY-----\n...'

    # Find a string and re Find addr
base_address = pattern_scan_all(p.process_handle, bytes_path, return_multiple=True)
```
候选列表为`[124839912, 124840872, 125032920]`

对这个列表遍历执行以下代码后，
```python
    for i in base_address:
        # base_address = base_address[len(base_address) - 1]
        bytes_path1 = (i).to_bytes(4, byteorder="little", signed=True)
        cc = pattern_scan_all(p.process_handle, bytes_path1, return_multiple=True)

        if cc[0] > wechat_addr:
            base_address = cc[0]
            break
```
三次执行获得的`cc`分别为`125161544`, `125162424`, `2055953372`。其中满足判断条件并对`base_address`重新赋值的`cc`为`2055953372`。

然而执行错误，报错信息为
```plain
Exception has occurred: MemoryReadError
Could not read memory at: 1868654968, length: 12 - GetLastError: 299

During handling of the above exception, another exception occurred:

  File "C:\Users\xct24\OneDrive\Creative\Programming\WeChatUserDB\get_info.py", line 86, in getuserinfo
    wxid = p.read_bytes(wxid_addr, int_wxid_len)
  File "C:\Users\xct24\OneDrive\Creative\Programming\WeChatUserDB\get_info.py", line 135, in get_key
    getuserinfo(p)
  File "C:\Users\xct24\OneDrive\Creative\Programming\WeChatUserDB\main.py", line 38, in <module>
    get_info.get_key()
```

此时本地变量有
```
base_address = 2055953372
bytes_path = b'-----BEGIN PUBLIC KEY-----\n...'
bytes_path1 = b'\xd8\xd9s\x07'
cc = [2055953372]
int_username_len = 0
int_wxid_len = 12
username = b''
wechat_addr = 2016935936
wxid_addr = 1868654968
```

另外我还尝试了去用`cc[0]`可能的值，即`125161544`, `125162424`, `2055953372`，直接赋值base_address, 但都没有效果。

感谢！

**Comment by Alive24** [comment]
多次重启后成功了
