### ISSUE TITLE
3.9.6.33 fail: OverflowError: int too big to convert

### ISSUE THREAD

**Issue by diablov** [x1hy9/WeChatUserDB#8]
$ python3 main.py -g
Traceback (most recent call last):
  File "R:\WeChatUserDB-main@x1hy9-2022\main.py", line 38, in <module>
    get_info.get_key()
  File "R:\WeChatUserDB-main@x1hy9-2022\get_info.py", line 135, in get_key
    getuserinfo(p)
  File "R:\WeChatUserDB-main@x1hy9-2022\get_info.py", line 72, in getuserinfo
    bytes_path1 = (i).to_bytes(4, byteorder="little", signed=True)
OverflowError: int too big to convert

**Comment by rolle0211** [comment]
> 
bytes_path1 = (i).to_bytes(4, byteorder="little", signed=True)
4换为8，就好了

**Comment by sbitpdc** [comment]
> > 
> 
> bytes_path1 = (i).to_bytes(4, byteorder="little", signed=True) 4换为8，就好了
 
这个错误是没出现了，但获取到的 username, wxid, sqliteKey都是空的，int_PublicKey_len是177，然后出现 pymem.exception.WinAPIError: Windows api error: error_coee: 299  和 pymem.exception.MemoryReadError: Could not read memory at :1238164964, length: 177 - GetLastError: 299错误。
